#!/usr/bin/env php
<?php

set_time_limit(60);

if ($argc !== 3) {
    echo "Usage: {$argv[0]} service hostname:port\n";
    exit(1);
}

$service = $argv[1];
$hostname = $argv[2];
$port = null;

if (strpos($hostname, ':') > 0) {
    list($hostname, $port) = explode(':', $argv[2]);
}

// Try to open a socket to the service provided
if (!@fsockopen($hostname,$port)) {
    printf('Waiting for %s service to be reachable at %s:%d', $service, $hostname, $port);
    echo PHP_EOL;

    do {
        echo '.';
        sleep(1);
    } while(!@fsockopen($hostname,$port));

    echo PHP_EOL;
}

printf('Service %s ready.', $service, $hostname, $port);
echo PHP_EOL;
exit(0);
