security:
    erase_credentials: false
    encoders:
        App\Entity\User:
            algorithm: bcrypt


    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email


    role_hierarchy:
        ROLE_ADMIN: ROLE_USER


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            http_basic: ~
            anonymous: ~
            user_checker: App\Security\UserChecker
            provider: user_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: /


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
